meta:
  environment: bosh-init-deployment-resource-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: just_install_packages
    networks:
      - name: bosh-init-deployment-resource1

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: bosh-init-deployment-resource1
  # Assumes up to 5 VMs, including 1 static and 4 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.3.0/30
    reserved:
    - 10.244.3.1
    static:
    - 10.244.3.2

  - cloud_properties:
      name: random
    range: 10.244.3.4/30
    reserved:
    - 10.244.3.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.8/30
    reserved:
    - 10.244.3.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.12/30
    reserved:
    - 10.244.3.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.16/30
    reserved:
    - 10.244.3.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.3.20/30
    reserved:
    - 10.244.3.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.24/30
    reserved:
    - 10.244.3.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.28/30
    reserved:
    - 10.244.3.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.32/30
    reserved:
    - 10.244.3.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.36/30
    reserved:
    - 10.244.3.37
    static: []
